# Generated by Django 4.1.6 on 2023-02-06 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_production_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentee',
            name='photo',
            field=models.ImageField(default='dog-5793625__480.jpg', upload_to='mentee_photo'),
        ),
    ]
