# Generated by Django 4.1.7 on 2023-03-03 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team_production_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_availability', to='team_production_system.mentor'),
        ),
        migrations.AlterField(
            model_name='session',
            name='mentee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentee_session', to='team_production_system.mentee'),
        ),
        migrations.AlterField(
            model_name='session',
            name='mentor_availability',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_session', to='team_production_system.availability'),
        ),
        migrations.AlterField(
            model_name='sessionrequestform',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request', to=settings.AUTH_USER_MODEL),
        ),
    ]
