# Generated by Django 4.1.7 on 2023-04-09 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team_production_system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='user',
        ),
    ]
