# Generated by Django 4.1.7 on 2023-03-21 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_production_system', '0002_alter_availability_mentor_alter_session_mentee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
