# Generated by Django 4.1.7 on 2023-03-21 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_production_system', '0003_alter_customuser_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photo'),
        ),
    ]
