# Generated by Django 4.2.1 on 2023-06-01 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team_production_system', '0006_alter_mentor_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_requested', models.BooleanField(default=False)),
                ('session_confirmed', models.BooleanField(default=False)),
                ('session_canceled', models.BooleanField(default=False)),
                ('fifteen_minute_alert', models.BooleanField(default=False)),
                ('sixty_minute_alert', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
