# Generated by Django 4.2.4 on 2023-09-01 19:43

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('team_production_system', '0009_availability_availability_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='skills',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('AI', 'AI'), ('AWS S3', 'AWS S3'), ('Bootstrap', 'Bootstrap'), ('Career Help', 'Career Help'), ('CSS', 'CSS'), ('Django', 'Django'), ('FastAPI', 'FastAPI'), ('Git', 'Git'), ('GitHub', 'GitHub'), ('HTML', 'HTML'), ('Insomnia', 'Insomnia'), ('Interview Help', 'Interview Help'), ('JavaScript', 'JavaScript'), ('MUI', 'MUI'), ('Other', 'Other'), ('PostgreSQL', 'PostgreSQL'), ('Postico', 'Postico'), ('Python', 'Python'), ('React', 'React'), ('Resume Help', 'Resume Help'), ('SQL', 'SQL'), ('Time Management', 'Time Management'), ('Vue.js', 'Vue.js')], default='HTML', max_length=157),
        ),
    ]
