# Generated by Django 4.2.5 on 2023-10-07 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_production_system', '0010_alter_mentor_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='team_number',
            field=models.IntegerField(default=0),
        ),
    ]
