# Generated by Django 4.2.5 on 2023-10-03 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("team_production_system", "0010_alter_mentor_skills"),
    ]

    operations = [
        migrations.AddField(
            model_name="availability",
            name="status",
            field=models.CharField(
                choices=[
                    ("Open", "Open"),
                    ("Requested", "Requested"),
                    ("Closed", "Closed"),
                ],
                default="Open",
                max_length=10,
            ),
        ),
    ]
