# Generated by Django 4.2.5 on 2023-10-04 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("team_production_system", "0011_availability_status"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="availability",
            name="availability_constraint",
        ),
        migrations.AddConstraint(
            model_name="availability",
            constraint=models.UniqueConstraint(
                fields=("mentor", "start_time"),
                name="availability_constraint",
                violation_error_message="Availability already exists.",
            ),
        ),
    ]
