# Generated by Django 4.2.5 on 2023-10-10 20:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("team_production_system", "0011_mentor_team_number"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="availability",
            name="availability_constraint",
        ),
        migrations.AddField(
            model_name="availability",
            name="status",
            field=models.CharField(
                choices=[
                    ("Open", "Open"),
                    ("Requested", "Requested"),
                    ("Confirmed", "Confirmed"),
                ],
                default="Open",
                max_length=10,
            ),
        ),
        migrations.AddConstraint(
            model_name="availability",
            constraint=models.UniqueConstraint(
                fields=("mentor", "start_time"),
                name="availability_constraint",
                violation_error_message="Availability already exists.",
            ),
        ),
    ]
