repos:
-   repo: https://github.com/PyCQA/isort
    rev: "5.12.0"
    hooks:
    -   id: isort
-   repo: https://github.com/psf/black
    rev: "23.10.1"
    hooks:
    -   id: black
-   repo: https://github.com/PyCQA/flake8
    rev: "6.1.0"
    hooks:
    -   id: flake8
-   repo: local
    hooks:
    -   id: branch-name-lint
        name: 'Branch Name Lint'
        entry: ./scripts/branch-name-lint.sh
        language: script
        always_run: true
        pass_filenames: false
    -   id: commit-msg-lint
        name: 'Commit Message Lint'
        entry: ./scripts/commit-msg-lint.sh
        language: script
        stages: [commit-msg]