repos:
-   repo: local
    hooks:
    -   id: branch-name-lint
        name: 'Branch Name Lint'
        entry: ./scripts/branch-name-lint.sh
        language: script
        always_run: true
        pass_filenames: false
    -   id: commit-msg-lint
        name: 'Commit Message Lint'
        entry: ./scripts/commit-msg-lint.sh
        language: script
        stages: [commit-msg]