version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    command: /start.sh
    # this volume is used to map the files and folders on the host to the container
    # so if we change code on the host, code in the docker container will also be changed
    volumes:
      - .:/app
    ports:
      - 8000:8000
    # env_file is used to manage the env variables of our project
    env_file:
      - ./config/.env
    environment:
      - DATABASE_URL=postgres://mentors:mentors@db:5432/mentors
    depends_on:
      - redis
      - db

  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=mentors
      - POSTGRES_USER=mentors
      - POSTGRES_PASSWORD=mentors
    ports:
      - 5433:5432

  redis:
    image: redis:7-alpine

  celery_worker:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    command: celery -A config.celery_settings worker -l info
    env_file:
      - ./config/.env
    environment:
      - DATABASE_URL=postgres://mentors:mentors@db:5432/mentors
      - CELERY_BROKER_URL=redis://redis:6379
      - CELERY_RESULT_BACKEND=redis://redis:6379
    volumes:
      - .:/app
    depends_on:
      - redis
      - db

  celery_beat:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    command: celery -A config.celery_settings beat -l debug
    env_file:
      - ./config/.env
    environment:
      - DATABASE_URL=postgres://mentors:mentors@db:5432/mentors
      - CELERY_BROKER_URL=redis://redis:6379
      - CELERY_RESULT_BACKEND=redis://redis:6379
    volumes:
      - .:/app
    depends_on:
      - redis
      - db

volumes:
  postgres_data: