version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    command: /start.sh
    # this volume is used to map the files and folders on the host to the container
    # so if we change code on the host, code in the docker container will also be changed
    volumes:
      - .:/app
    ports:
      - 8000:8000
    # env_file is used to manage the env variables of our project
    env_file:
      - ./config/.env
    environment:
      - DATABASE_NAME=mentors
      - DATABASE_USER=mentors
      - DATABASE_PASSWORD=mentors
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
    depends_on:
      - redis
      - db

  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=mentors
      - POSTGRES_USER=mentors
      - POSTGRES_PASSWORD=mentors
    ports:
      - 5432:5432

  redis:
    image: redis:7-alpine

  celery_worker:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    command: celery -A celery.config worker -l INFO
    environment:
      - SQL_DATABASE=mentors
      - SQL_USER=mentors
      - SQL_PASSWORD=mentors
      - SQL_HOST=db
    volumes:
      - .:/app
    depends_on:
      - redis
      - db

  celery_beat:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    command: celery -A celery.config beat -l debug
    environment:
      - SQL_DATABASE=mentors
      - SQL_USER=mentors
      - SQL_PASSWORD=mentors
      - SQL_HOST=db
    volumes:
      - .:/app
    depends_on:
      - redis
      - db

volumes:
  postgres_data: