[tool.black]
line-length = 88
skip-string-normalization = 1
[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
line_length = 88
skip = ["./team_production_system/migrations/", ".gitignore", ".dockerignore"]